name: doctrine/quality-checks-report
author: Doctrine Team
description: Runs static analzers and posts results with Github Checks API
runs:
    using: docker
    image: Dockerfile
branding:
    icon: arrow-right-circle
    color: orange
